### ISSUE TITLE
source code from examples

### ISSUE THREAD

**Issue by nafergo** [phoenixbf/aton#8]
Hi
Is the sourcecode from these projects/examples 
http://osiris.itabc.cnr.it/scenebaker/index.php/projects/aton/

available?

I'm not a developer, starting from  examples would be great :) and these examples pretty much cover my plans :) 
- 360 with a system that allow to toggle layers
- 3d photogrammetry from excavation and a system that allow to toggle layers
- 
thx

**Comment by phoenixbf** [comment]
These use the official ATON front-end ("Hathor") that allows you to publish both pure 3D content and 360 very easily. We'll soon create tutorials on the website on this topic.
Otherwise you can find here (https://aton.ispc.cnr.it/examples/) some basic examples with commented code.
We'll soon add a few samples dealing specifically with multiple layers and 360!
